#!/usr/bin/env sh
# global settings

# yabai -m config mouse_drop_action swap
# New window spawns to the left if vertical split, or top if horizontal split
# yabai -m config window_placement first_child
# New window spawns to the right if vertical split, or bottom if horizontal split
# yabai -m config window_placement second_child

# general space settings
yabai -m config layout         bsp
yabai -m config top_padding    0
yabai -m config bottom_padding 0
yabai -m config left_padding   0
yabai -m config right_padding  0
yabai -m config window_gap     5

# Float windows
yabai -m rule --add app="Neovide" manage=off
yabai -m rule --add app="neovide" manage=off

# Mac Os App
yabai -m rule --add app="Activity Monitor" manage=off
yabai -m rule --add app="App Store" manage=off
yabai -m rule --add app="Archive Utility" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Messages" manage=off
yabai -m rule --add app="Note" manage=off
yabai -m rule --add app="Photos" manage=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="System Information" manage=off
yabai -m rule --add app="Preview" manage=off
yabai -m rule --add app="FaceTime" manage=off
yabai -m rule --add app="Weather" manage=off
yabai -m rule --add app="Dictionary" manage=off
yabai -m rule --add app="Safari" manage=off
yabai -m rule --add app="VMware Horizon Client" manage=off

# 3rd party App
yabai -m rule --add app="Docker" manage=off
yabai -m rule --add app="Zalo" manage=off
yabai -m rule --add app="Brave" manage=off
yabai -m rule --add app="Slack" manage=off
yabai -m rule --add app="Messenger" manage=off
yabai -m rule --add app="Microsoft Teams" manage=off
yabai -m rule --add app="DBeaver" manage=off
yabai -m rule --add app="Alfred Preferences" manage=off
yabai -m rule --add app="Logi Options+" manage=off
yabai -m rule --add app="CleanMyMac X" manage=off
yabai -m rule --add app="League of Legends" manage=off
yabai -m rule --add app="Skype" manage=off
